"""optional fields in shopping list entry

Revision ID: 00caa08644a0
Revises: aa8ca5e250d4
Create Date: 2026-08-15 18:45:46.407845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00caa08644a0'
down_revision: Union[str, Sequence[str], None] = 'aa8ca5e250d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_list_entries', 'quantity',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('shopping_list_entries', 'unit',
               existing_type=postgresql.ENUM('szt.', 'opakowania', 'kg', 'g', 'l', 'ml', '', name='custom_unit_enum'),
               nullable=True)
    op.alter_column('shopping_list_entries', 'extra_notes',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_list_entries', 'extra_notes',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('shopping_list_entries', 'unit',
               existing_type=postgresql.ENUM('szt.', 'opakowania', 'kg', 'g', 'l', 'ml', '', name='custom_unit_enum'),
               nullable=False)
    op.alter_column('shopping_list_entries', 'quantity',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
