"""optional fields in changelog

Revision ID: 700a92e2a264
Revises: daf2db1cdf4b
Create Date: 2026-08-14 15:32:14.232903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700a92e2a264'
down_revision: Union[str, Sequence[str], None] = 'daf2db1cdf4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('changelog', 'shopping_list_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('changelog', 'product_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('changelog', 'author',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('changelog', 'author',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('changelog', 'product_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('changelog', 'shopping_list_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
