"""initial_migration

Revision ID: daf2db1cdf4b
Revises: 
Create Date: 2026-08-08 15:12:01.704141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf2db1cdf4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('name', sa.String(length=330), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shopping_lists',
    sa.Column('title', sa.String(length=330), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('changelog',
    sa.Column('shopping_list_id', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.String(length=128), nullable=False),
    sa.Column('change_title', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_list_entries',
    sa.Column('shopping_list_id', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.Enum('szt.', 'opakowania', 'kg', 'g', 'l', 'ml', '', name='custom_unit_enum'), nullable=False),
    sa.Column('extra_notes', sa.String(length=120), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_list_entries')
    op.drop_table('changelog')
    op.drop_table('shopping_lists')
    op.drop_table('products')
    # ### end Alembic commands ###
